### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by WnDSolutions** [augustsh/pQueue#1]
Hello,

I don't know if that's a problem or good/bad for the server, but I have my console getting spammed with ``[]`` only with your resource.

How can i fix/stop this?

Thanks!

![image](https://user-images.githubusercontent.com/6540983/108606974-3f70ad80-73c6-11eb-8c45-5d38079746d7.png)

**Comment by augustsh** [comment]
Hey, seems like I forgot to remove an interval used during testing that logged the graceList to console. Just pushed a fix :)
